name: OPIslandsQuestSystem
version: '1.1'
main: com.quests.OPIslandsQuestSystem.Quest
api-version: '1.21'
authors: [ Paulantis ]
description: A Minecraft Quest System
commands:
  quest:
    description: Öffnet ein Quest Interface
    usage: /quest
    aliases: [q, quests]